apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  labels:
    app: prometheus-storage
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 10Gi