apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
   - port: 9090
     targetPort: 9090
     nodePort: 31090